In [17]:
import pandas as pd
import numpy as np

names = [
    "Ведьмак",
    "1984",
    "Робинзон Крузо",
    "Властелин Колец",
    "Капитал"
]
isbn = [
    "978-5-271-40351-4",
    "978-5-9614-2525-3",
    "978-5-17-090731-1",
    "978-5-17-089322-5",
    "978-5-17-169678-8"
]
authors = [
    "Анджей Сапковский",
    "Джордж Оруэлл",
    "Даниэль Дефо",
    "Джон Рональд Руэл Толкин",
    "Карл Генрих Маркс"
]
price = [
    "2670.00",
    "600.90",
    "540.10",
    "2270.60",
    "1600.10"
]
dfbooks = pd.DataFrame({
    'Название': names,
    'Автор': authors,
    'Цена': price
})

In [18]:

series1 = pd.Series(names, index=isbn, dtype="str", name="Boocks")
print(series1.to_string())
print()

series2 = pd.Series(authors, index=isbn, dtype="str", name="Authors")
print(series2.to_string())
print()

series3 = pd.Series(price, index=isbn, dtype="float", name="Price")
print(series3.to_string())
print()

series4 = pd.Series(authors, index=names, dtype="str", name="Authors")
print(series4.to_string())

978-5-271-40351-4            Ведьмак
978-5-9614-2525-3               1984
978-5-17-090731-1     Робинзон Крузо
978-5-17-089322-5    Властелин Колец
978-5-17-169678-8            Капитал

978-5-271-40351-4           Анджей Сапковский
978-5-9614-2525-3               Джордж Оруэлл
978-5-17-090731-1                Даниэль Дефо
978-5-17-089322-5    Джон Рональд Руэл Толкин
978-5-17-169678-8           Карл Генрих Маркс

978-5-271-40351-4    2670.0
978-5-9614-2525-3     600.9
978-5-17-090731-1     540.1
978-5-17-089322-5    2270.6
978-5-17-169678-8    1600.1

Ведьмак                   Анджей Сапковский
1984                          Джордж Оруэлл
Робинзон Крузо                 Даниэль Дефо
Властелин Колец    Джон Рональд Руэл Толкин
Капитал                   Карл Генрих Маркс

In [19]:
print(min(series3))
print(max(series3))
print(round(series3.mean(),2))

540.1
2670.0
1536.34

In [20]:
df1 = pd.DataFrame({
    'Издательство': ['АСТ', 'Эксмо', 'Питер', 'МИФ', 'Альпина'],
    'Год издания': [2020, 2021, 2019, 2022, 2023],
    'Количество страниц': [350, 420, 280, 510, 310]
}, index=isbn)

display(df1)

df2 = pd.DataFrame({
    'Название': series1,
    'Автор': series2,
    'Цена': series3
})

display(df2)

df3 = pd.concat([df1, df2], axis=1)

display(df3)

display(pd.DataFrame({'Метки строк': df3.index}))
display(pd.DataFrame({'Метки столбцов': df3.columns}))
display(pd.DataFrame(df3.values, index=df3.index, columns=df3.columns))

display(df3.head(2))

display(df3.iloc[1:4])

display(df3[['Название']])

display(df3[['Цена']])

display(pd.DataFrame({'Название': [df3.loc[isbn[0], 'Название']]}, index=[isbn[0]]))

display(pd.DataFrame({'Автор': [df3.iloc[1]['Автор']]}, index=[df3.index[1]]))

                  Издательство  Год издания  Количество страниц
978-5-271-40351-4          АСТ         2020                 350
978-5-9614-2525-3        Эксмо         2021                 420
978-5-17-090731-1        Питер         2019                 280
978-5-17-089322-5          МИФ         2022                 510
978-5-17-169678-8      Альпина         2023                 310

                          Название                     Автор    Цена
978-5-271-40351-4          Ведьмак         Анджей Сапковский  2670.0
978-5-9614-2525-3             1984             Джордж Оруэлл   600.9
978-5-17-090731-1   Робинзон Крузо              Даниэль Дефо   540.1
978-5-17-089322-5  Властелин Колец  Джон Рональд Руэл Толкин  2270.6
978-5-17-169678-8          Капитал         Карл Генрих Маркс  1600.1

                  Издательство  Год издания  Количество страниц         Название                     Автор    Цена
978-5-271-40351-4          АСТ         2020                 350          Ведьмак         Анджей Сапковский  2670.0
978-5-9614-2525-3        Эксмо         2021                 420             1984             Джордж Оруэлл   600.9
978-5-17-090731-1        Питер         2019                 280   Робинзон Крузо              Даниэль Дефо   540.1
978-5-17-089322-5          МИФ         2022                 510  Властелин Колец  Джон Рональд Руэл Толкин  2270.6
978-5-17-169678-8      Альпина         2023                 310          Капитал         Карл Генрих Маркс  1600.1

         Метки строк
0  978-5-271-40351-4
1  978-5-9614-2525-3
2  978-5-17-090731-1
3  978-5-17-089322-5
4  978-5-17-169678-8

       Метки столбцов
0        Издательство
1         Год издания
2  Количество страниц
3            Название
4               Автор
5                Цена

                  Издательство Год издания Количество страниц         Название                     Автор    Цена
978-5-271-40351-4          АСТ        2020                350          Ведьмак         Анджей Сапковский  2670.0
978-5-9614-2525-3        Эксмо        2021                420             1984             Джордж Оруэлл   600.9
978-5-17-090731-1        Питер        2019                280   Робинзон Крузо              Даниэль Дефо   540.1
978-5-17-089322-5          МИФ        2022                510  Властелин Колец  Джон Рональд Руэл Толкин  2270.6
978-5-17-169678-8      Альпина        2023                310          Капитал         Карл Генрих Маркс  1600.1

                  Издательство  Год издания  Количество страниц Название              Автор    Цена
978-5-271-40351-4          АСТ         2020                 350  Ведьмак  Анджей Сапковский  2670.0
978-5-9614-2525-3        Эксмо         2021                 420     1984      Джордж Оруэлл   600.9

                  Издательство  Год издания  Количество страниц         Название                     Автор    Цена
978-5-9614-2525-3        Эксмо         2021                 420             1984             Джордж Оруэлл   600.9
978-5-17-090731-1        Питер         2019                 280   Робинзон Крузо              Даниэль Дефо   540.1
978-5-17-089322-5          МИФ         2022                 510  Властелин Колец  Джон Рональд Руэл Толкин  2270.6

                          Название
978-5-271-40351-4          Ведьмак
978-5-9614-2525-3             1984
978-5-17-090731-1   Робинзон Крузо
978-5-17-089322-5  Властелин Колец
978-5-17-169678-8          Капитал

                     Цена
978-5-271-40351-4  2670.0
978-5-9614-2525-3   600.9
978-5-17-090731-1   540.1
978-5-17-089322-5  2270.6
978-5-17-169678-8  1600.1

                  Название
978-5-271-40351-4  Ведьмак

                           Автор
978-5-9614-2525-3  Джордж Оруэлл